# Chinese translations for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-10-13 19:12+0800\n"
"PO-Revision-Date: 2022-06-23 17:41+0800\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: zh\n"
"Language-Team: zh <LL@li.org>\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.3\n"

#: common/errorcode/errors/graph_error.py:8
#: common/errorcode/errors/graph_error.py:115
#: common/errorcode/errors/graph_error.py:127
#: common/errorcode/errors/graph_error.py:133
msgid "Parameter [arg] Error."
msgstr "参数[arg]错误"

#: common/errorcode/errors/graph_error.py:9
#: common/errorcode/errors/graph_error.py:21
#: common/errorcode/errors/graph_error.py:27
#: common/errorcode/errors/graph_error.py:51
#: common/errorcode/errors/graph_error.py:63
#: common/errorcode/errors/graph_error.py:75
#: common/errorcode/errors/graph_error.py:87
#: common/errorcode/errors/graph_error.py:93
#: common/errorcode/errors/graph_error.py:105
#: common/errorcode/errors/graph_error.py:111
#: common/errorcode/errors/lexicon_error.py:16
#: common/errorcode/errors/lexicon_error.py:22
#: common/errorcode/errors/lexicon_error.py:28
#: common/errorcode/errors/lexicon_error.py:70
#: common/errorcode/errors/lexicon_error.py:76
#: common/errorcode/errors/lexicon_error.py:83
#: common/errorcode/errors/lexicon_error.py:89
#: common/errorcode/errors/lexicon_error.py:96
#: common/errorcode/errors/lexicon_error.py:102
#: common/errorcode/errors/lexicon_error.py:109
#: common/errorcode/errors/lexicon_error.py:115
#: common/errorcode/errors/lexicon_error.py:140
#: common/errorcode/errors/lexicon_error.py:146
#: common/errorcode/errors/lexicon_error.py:153
#: common/errorcode/errors/lexicon_error.py:159
#: common/errorcode/errors/lexicon_error.py:165
#: common/errorcode/errors/lexicon_error.py:177
#: common/errorcode/errors/lexicon_error.py:190
#: common/errorcode/errors/lexicon_error.py:196
#: common/errorcode/errors/lexicon_error.py:216
#: common/errorcode/errors/lexicon_error.py:222
#: common/errorcode/errors/lexicon_error.py:228
#: common/errorcode/errors/lexicon_error.py:236
#: common/errorcode/errors/lexicon_error.py:242
#: common/errorcode/errors/lexicon_error.py:249
#: common/errorcode/errors/lexicon_error.py:255
#: common/errorcode/errors/lexicon_error.py:274
#: common/errorcode/errors/lexicon_error.py:288
#: common/errorcode/errors/lexicon_error.py:294
#: common/errorcode/errors/lexicon_error.py:301
#: common/errorcode/errors/lexicon_error.py:307
#: common/errorcode/errors/lexicon_error.py:368
#: common/errorcode/errors/lexicon_error.py:374
msgid "Please check your parameter again."
msgstr "请重新检查输入参数"

#: common/errorcode/errors/graph_error.py:14
#: common/errorcode/errors/graph_error.py:56
#: common/errorcode/errors/graph_error.py:80
#: common/errorcode/errors/graph_error.py:98
#: common/errorcode/errors/graph_error.py:122
#: common/errorcode/errors/graph_error.py:146
msgid "[cause]"
msgstr ""

#: common/errorcode/errors/graph_error.py:15
#: common/errorcode/errors/graph_error.py:57
#: common/errorcode/errors/graph_error.py:81
#: common/errorcode/errors/graph_error.py:99
#: common/errorcode/errors/graph_error.py:123
#: common/errorcode/errors/graph_error.py:147
#: common/errorcode/errors/intelligence_error.py:9
#: common/errorcode/errors/intelligence_error.py:15
#: common/errorcode/errors/intelligence_error.py:47
#: common/errorcode/errors/intelligence_error.py:53
#: common/errorcode/errors/intelligence_error.py:59
#: common/errorcode/errors/intelligence_error.py:65
msgid "Please contact the developers."
msgstr "请联系开发人员"

#: common/errorcode/errors/graph_error.py:19
#: common/errorcode/errors/graph_error.py:20
msgid "graphid [graphid] not exists."
msgstr "graphid [graphid] 不存在"

#: common/errorcode/errors/graph_error.py:25
msgid "key type error"
msgstr "key类型错误"

#: common/errorcode/errors/graph_error.py:26
msgid "key should be list of string"
msgstr "key应为字符串列表"

#: common/errorcode/errors/graph_error.py:31
#: common/errorcode/errors/graph_error.py:32
msgid "graphdb id [graphdb_id] not exists"
msgstr "图数据库id [graphdb_id] 不存在"

#: common/errorcode/errors/graph_error.py:33
msgid "please config your graphdb again."
msgstr "请重新配置图数据库"

#: common/errorcode/errors/graph_error.py:43
msgid "these keys are not supported: [unsupported_key]"
msgstr "这些字段不支持: [unsupported_key]"

#: common/errorcode/errors/graph_error.py:44
msgid "some keys are not supported."
msgstr "key中有不支持的字段"

#: common/errorcode/errors/graph_error.py:45
msgid "please check your parameter key again."
msgstr "请检查传入的参数key"

#: common/errorcode/errors/graph_error.py:50
#: common/errorcode/errors/graph_error.py:74
#: common/errorcode/errors/graph_error.py:92
msgid "argument [arg] error"
msgstr "参数[arg]错误"

#: common/errorcode/errors/graph_error.py:61
#: common/errorcode/errors/graph_error.py:62
#: common/errorcode/errors/graph_error.py:85
#: common/errorcode/errors/graph_error.py:86
#: common/errorcode/errors/graph_error.py:103
#: common/errorcode/errors/graph_error.py:104
msgid "graph id [graphid] not exists"
msgstr "graph id [graphid] 不存在"

#: common/errorcode/errors/graph_error.py:67
#: common/errorcode/errors/graph_error.py:68
msgid "ontology id [otl_id] not exists"
msgstr "本体id [otl_id] 不存在"

#: common/errorcode/errors/graph_error.py:69
msgid "Please config the ontology."
msgstr "请配置本体"

#: common/errorcode/errors/graph_error.py:109
#: common/errorcode/errors/graph_error.py:110
msgid "[class_type] [name] not exists"
msgstr "[class_type] [name] 不存在"

#: common/errorcode/errors/graph_error.py:116
#: common/errorcode/errors/graph_error.py:128
#: common/errorcode/errors/graph_error.py:134
msgid "parameter [arg] not exists or invalid"
msgstr "参数 [arg] 不存在或者非法"

#: common/errorcode/errors/graph_error.py:117
#: common/errorcode/errors/graph_error.py:129
#: common/errorcode/errors/graph_error.py:135
#: common/errorcode/errors/graph_error.py:141
#: common/errorcode/errors/graph_error.py:153
#, fuzzy
msgid "please ensure parameter [arg] exists and valid"
msgstr "请检查传入的参数key"

#: common/errorcode/errors/graph_error.py:139
#: common/errorcode/errors/graph_error.py:140
#, fuzzy
msgid "Parameter [arg] too big please lower than [max]"
msgstr "参数 [arg] 太大, 请选择小于 [max]"

#: common/errorcode/errors/graph_error.py:151
#: common/errorcode/errors/graph_error.py:152
msgid "Parameter [arg] not allow, please choose [allowed]"
msgstr "参数 [arg] 不被允许, 请选择 [allowed]"

#: common/errorcode/errors/graphdb_error.py:9
#: common/errorcode/errors/graphdb_error.py:33
msgid "Please check whether the OrientDB request information is correct."
msgstr "请检查OrientDB请求信息是否正确"

#: common/errorcode/errors/graphdb_error.py:15
#: common/errorcode/errors/graphdb_error.py:39
#: common/errorcode/errors/graphdb_error.py:45
msgid "Please check whether the Nebula request information is correct."
msgstr "请检查Nebula请求信息是否正确"

#: common/errorcode/errors/graphdb_error.py:21
msgid "Please check whether your GraphDB service is running normally."
msgstr "请检查图数据库服务是否正常运行"

#: common/errorcode/errors/graphdb_error.py:27
msgid "Please check whether your DB name is correct."
msgstr "请检查图数据库名称是否正确"

#: common/errorcode/errors/intelligence_error.py:19
#: common/errorcode/errors/intelligence_error.py:20
msgid "knowledge graph is waiting build, please calculate after building"
msgstr "知识图谱在等待运行中，构建完成后可进行计算。"

#: common/errorcode/errors/intelligence_error.py:21
#: common/errorcode/errors/intelligence_error.py:27
#: common/errorcode/errors/intelligence_error.py:33
#: common/errorcode/errors/intelligence_error.py:41
#: common/errorcode/errors/intelligence_error.py:71
msgid "Please check graph status"
msgstr "请检查图谱状态"

#: common/errorcode/errors/intelligence_error.py:25
#: common/errorcode/errors/intelligence_error.py:26
msgid "knowledge graph is building, please calculate after building"
msgstr "知识图谱正在运行中，构建完成后可进行计算。"

#: common/errorcode/errors/intelligence_error.py:31
#: common/errorcode/errors/intelligence_error.py:32
msgid "knowledge graph is configuring build, please calculate after building"
msgstr "知识图谱正在配置中，构建完成后可进行计算。"

#: common/errorcode/errors/intelligence_error.py:37
#: common/errorcode/errors/intelligence_error.py:39
#, fuzzy
msgid ""
"knowledge graph store in NebulaGraph, if you need intelligence score, "
"please calculate after building successfully"
msgstr "由于知识图谱存储于nebula数据库中，若需计算，请先将图谱构建成功。"

#: common/errorcode/errors/intelligence_error.py:45
msgid "call async task service error"
msgstr "调用异步任务服务错误"

#: common/errorcode/errors/intelligence_error.py:46
#: common/errorcode/errors/intelligence_error.py:52
#: common/errorcode/errors/intelligence_error.py:58
#: common/errorcode/errors/intelligence_error.py:64
#: common/errorcode/errors/network_error.py:8
#: common/errorcode/errors/network_error.py:14
msgid "[detail]"
msgstr ""

#: common/errorcode/errors/intelligence_error.py:51
msgid "async task service internal error"
msgstr "异步任务服务内部错误"

#: common/errorcode/errors/intelligence_error.py:57
msgid "graph intelligence info query error"
msgstr "图谱智商信息查询错误"

#: common/errorcode/errors/intelligence_error.py:63
msgid "network intelligence info query error"
msgstr "知识网络智商信息查询错误"

#: common/errorcode/errors/intelligence_error.py:69
#: common/errorcode/errors/intelligence_error.py:70
#, fuzzy
msgid ""
"knowledge graph status invalid, please calculate after building "
"successfully"
msgstr "知识图谱构建状态非法, 请构建后再计算"

#: common/errorcode/errors/intelligence_error.py:75
#: common/errorcode/errors/intelligence_error.py:76
#, fuzzy
msgid "knowledge network [knw_id] not exists"
msgstr "本体id [otl_id] 不存在"

#: common/errorcode/errors/intelligence_error.py:77
#, fuzzy
msgid "please config your knowledge network again."
msgstr "请重新配置图数据库"

#: common/errorcode/errors/lexicon_error.py:9
msgid "Please check the database connection."
msgstr "抢检查数据库连接情况"

#: common/errorcode/errors/lexicon_error.py:21
msgid ""
"The specified knowledge_id [knowledge_id] does not exist, lexicon "
"creation failed!"
msgstr "指定的知识网络id [knowledge_id] 不存在，词库创建失败"

#: common/errorcode/errors/lexicon_error.py:27
#: common/errorcode/errors/lexicon_error.py:227
msgid ""
"Lexicon name [lexicon_name] already exists and cannot be created "
"repeatedly."
msgstr "词库名称 [lexicon_name] 已经存在，不可以重复创建"

#: common/errorcode/errors/lexicon_error.py:33
#: common/errorcode/errors/lexicon_error.py:312
msgid "[ErrorDetails]"
msgstr ""

#: common/errorcode/errors/lexicon_error.py:34
msgid "Please check the type, size and content format of the uploaded file."
msgstr "请核对上传文件的大小、类型以及内容格式"

#: common/errorcode/errors/lexicon_error.py:39
#: common/errorcode/errors/lexicon_error.py:324
msgid "Only one file can be selected at most."
msgstr "仅支持上传一个文件"

#: common/errorcode/errors/lexicon_error.py:40
#: common/errorcode/errors/lexicon_error.py:46
#: common/errorcode/errors/lexicon_error.py:325
#: common/errorcode/errors/lexicon_error.py:331
#: common/errorcode/errors/lexicon_error.py:349
msgid "Please select upload file again."
msgstr "请重新选择上传文件"

#: common/errorcode/errors/lexicon_error.py:45
#: common/errorcode/errors/lexicon_error.py:330
msgid "The file format only supports txt and CSV."
msgstr "文件格式错误，仅支持txt、csv"

#: common/errorcode/errors/lexicon_error.py:51
#: common/errorcode/errors/lexicon_error.py:336
msgid "File content format error."
msgstr "文件内容格式错误"

#: common/errorcode/errors/lexicon_error.py:52
#: common/errorcode/errors/lexicon_error.py:337
msgid ""
"Please check the content and format of the document according to the "
"template."
msgstr "请按照模板核对文件内容格式"

#: common/errorcode/errors/lexicon_error.py:57
#: common/errorcode/errors/lexicon_error.py:342
msgid "The file only supports UTF-8 encoding."
msgstr "上传文件只支持UTF-8编码"

#: common/errorcode/errors/lexicon_error.py:58
#: common/errorcode/errors/lexicon_error.py:343
msgid "Please confirm the file code and reselect the file."
msgstr "请确认文件编码，重新选择文件"

#: common/errorcode/errors/lexicon_error.py:63
#: common/errorcode/errors/lexicon_error.py:354
msgid "The amount of uploaded file data exceeds."
msgstr "上传文件数据量超出"

#: common/errorcode/errors/lexicon_error.py:64
#: common/errorcode/errors/lexicon_error.py:355
msgid ""
"The uploaded file must be less than 10M and the number of lines must be "
"less than 350000."
msgstr "文件大小不可超过10M，且在35万行以内"

#: common/errorcode/errors/lexicon_error.py:75
msgid ""
"The specified knowledge_id [knowledge_id] does not exist, get labels "
"failed!"
msgstr "指定的知识网络id [knowledge_id] 不存在，获取标签失败"

#: common/errorcode/errors/lexicon_error.py:88
msgid ""
"The specified knowledge_id [knowledge_id] does not exist, get lexicon "
"failed!"
msgstr "指定的知识网络id [knowledge_id] 不存在，获取词库信息失败"

#: common/errorcode/errors/lexicon_error.py:101
msgid "The specified lexicon id [lexicon_id] does not exist, get lexicon failed!"
msgstr "指定的词库id [lexicon_id] 不存在，获取词库信息失败"

#: common/errorcode/errors/lexicon_error.py:114
#: common/errorcode/errors/lexicon_error.py:139
#: common/errorcode/errors/lexicon_error.py:158
#: common/errorcode/errors/lexicon_error.py:195
#: common/errorcode/errors/lexicon_error.py:221
#: common/errorcode/errors/lexicon_error.py:241
#: common/errorcode/errors/lexicon_error.py:254
#: common/errorcode/errors/lexicon_error.py:293
#: common/errorcode/errors/lexicon_error.py:306
#: common/errorcode/errors/lexicon_error.py:373
msgid "The specified lexicon id [lexicon_id] does not exist."
msgstr "指定的词库id [lexicon_id] 不存在"

#: common/errorcode/errors/lexicon_error.py:120
msgid "The format of the new data [data] does not match the original data"
msgstr "新数据 [data] 和词库中已有数据的格式不匹配"

#: common/errorcode/errors/lexicon_error.py:121
#: common/errorcode/errors/lexicon_error.py:127
#: common/errorcode/errors/lexicon_error.py:171
#: common/errorcode/errors/lexicon_error.py:202
#: common/errorcode/errors/lexicon_error.py:319
#, fuzzy
msgid "Please check lexicon format again."
msgstr "请重新检查输入参数"

#: common/errorcode/errors/lexicon_error.py:126
msgid "The newly added word [data] already exists."
msgstr "新增的词汇[data]已经存在."

#: common/errorcode/errors/lexicon_error.py:132
msgid "lexicon [lexicon_id] status is running, cannot insert."
msgstr "running状态的词库[lexicon_id]，无法新增词汇"

#: common/errorcode/errors/lexicon_error.py:133
#: common/errorcode/errors/lexicon_error.py:183
#: common/errorcode/errors/lexicon_error.py:208
#: common/errorcode/errors/lexicon_error.py:267
#: common/errorcode/errors/lexicon_error.py:361
msgid "lexicon status is running, please make sure lexicon status is correct."
msgstr "词库状态running，请确保词库状态正确"

#: common/errorcode/errors/lexicon_error.py:164
msgid "The specified lexicon word [lexicon_word] does not exist."
msgstr "指定的词库词汇 [lexicon_word] 不存在"

#: common/errorcode/errors/lexicon_error.py:170
msgid "New data [new_info] and original data [old_info] fields are inconsistent."
msgstr "新数据 [new_info] 和 已有数据 [old_info] 的字段不一致"

#: common/errorcode/errors/lexicon_error.py:176
msgid "The modified word [lexicon_word] already exists."
msgstr "修改后的词汇[lexicon_word]已经存在."

#: common/errorcode/errors/lexicon_error.py:182
msgid "lexicon [lexicon_id] status is running, cannot edit word."
msgstr "running状态的词库[lexicon_id]，无法编辑词汇"

#: common/errorcode/errors/lexicon_error.py:201
msgid "There is no deleted data [delete_data] in the specified lexicon."
msgstr "需要删除的词 [delete_data] 在指定的词库中不存在"

#: common/errorcode/errors/lexicon_error.py:207
msgid "lexicon [lexicon_id] status is running, cannot delete word."
msgstr "running状态的词库[lexicon_id]，无法删除词汇"

#: common/errorcode/errors/lexicon_error.py:266
msgid "lexicon [lexicon_id] status is running, cannot export."
msgstr "running状态的词库[lexicon_id]，无法导出"

#: common/errorcode/errors/lexicon_error.py:280
msgid "Please see the error prompt for details."
msgstr "请查看详细的错误提示信息"

#: common/errorcode/errors/lexicon_error.py:313
#, fuzzy
msgid "Please check the type and size of the uploaded file."
msgstr "请核对上传文件的大小、类型以及内容格式"

#: common/errorcode/errors/lexicon_error.py:318
msgid "New data and original data fields are inconsistent"
msgstr "导入的数据和词库已有数据字段不一致"

#: common/errorcode/errors/lexicon_error.py:348
msgid "Select at least one file."
msgstr "请至少选择一个文件"

#: common/errorcode/errors/lexicon_error.py:360
msgid "lexicon [lexicon_id] status is running, cannot import words."
msgstr "running状态的词库[lexicon_id]，无法导入词汇"

#: common/errorcode/errors/network_error.py:7
#, fuzzy
msgid "Parameters Error!"
msgstr "参数[arg]错误"

#: common/errorcode/errors/network_error.py:9
#: common/errorcode/errors/network_error.py:15
#, fuzzy
msgid "Please check your parameters."
msgstr "请重新检查输入参数"

#: common/errorcode/errors/network_error.py:13
msgid "[description]"
msgstr ""

#~ msgid "File format conflict, all file structures need to be unified."
#~ msgstr "字段格式冲突，所有文件的内容结构需要一致"

#~ msgid "The file format only supports CSV and TXT."
#~ msgstr "上传文件仅支持csv和txt."

#~ msgid "The maximum number of uploaded file is 5;"
#~ msgstr "上传文件个数最多为5个."

#~ msgid "Failed to get file."
#~ msgstr "获取文件失败"

#~ msgid "Please check graph build status"
#~ msgstr "请检查图谱构建状态"

#~ msgid "parameter [arg] error"
#~ msgstr "参数 [arg] 错误"

